export const LOGS = [
  {
    date: '23-12-29',
    time: '12:17:29',
    tag: '[main]',
    level: 'INFO',
    type: 'm.c.s.o.a.MxObuGblOrqAppianApplication',
    message:
      'Starting MxObuGblOrqAppianApplication v1.0.6-SNAPSHOT using Java 17 with PID 1 (/opt/app/mx-obu-gbl-orq-appian-1.0.6-20231229.181653-6.jar started by 1003000000 in /opt/produban/start.d)',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:29',
    tag: '[main]',
    level: 'INFO',
    type: 'm.c.s.o.a.MxObuGblOrqAppianApplication',
    message:
      'No active profile set, falling back to 1 default profile: "default"',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:32',
    tag: '[main]',
    level: 'INFO',
    type: 'o.s.d.r.c.RepositoryConfigurationDelegate',
    message: 'Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:32',
    tag: '[main]',
    level: 'INFO',
    type: 'o.s.d.r.c.RepositoryConfigurationDelegate',
    message:
      'Finished Spring Data repository scanning in 108 ms. Found 2 MongoDB repository interfaces.',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:33',
    tag: '[main]',
    level: 'INFO',
    type: 'o.s.b.w.e.tomcat.TomcatWebServer',
    message: 'Tomcat initialized with port 8080 (http)',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:33',
    tag: '[main]',
    level: 'INFO',
    type: 'o.a.coyote.http11.Http11NioProtocol',
    message: 'Initializing ProtocolHandler ["http-nio-8080"]',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:33',
    tag: '[main]',
    level: 'INFO',
    type: 'o.a.catalina.core.StandardService',
    message: 'Starting service [Tomcat]',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:33',
    tag: '[main]',
    level: 'INFO',
    type: 'o.a.catalina.core.StandardEngine',
    message: 'Starting Servlet engine: [Apache Tomcat/10.1.16]',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:34',
    tag: '[main]',
    level: 'INFO',
    type: 'o.a.c.c.C.[Tomcat].[localhost].[/]',
    message: 'Initializing Spring embedded WebApplicationContext',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:34',
    tag: '[main]',
    level: 'INFO',
    type: 'o.s.b.w.s.c.ServletWebServerApplicationContext',
    message: 'Root WebApplicationContext: initialization completed in 4621 ms',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:36',
    tag: '[main]',
    level: 'INFO',
    type: 'org.mongodb.driver.cluster',
    message:
      'Adding discovered server 180.181.49.243:28000 to client view of cluster',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:36',
    tag: '[main]',
    level: 'INFO',
    type: 'org.mongodb.driver.client',
    message:
      'MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync|spring-boot", "version": "4.11.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "4.18.0-372.59.1.el8_6.x86_64"}, "platform": "Java/Oracle Corporation/17+35-2724"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName=\'dehtmili\', source=\'admin\', password=<hidden>, mechanismProperties=<hidden>}, transportSettings=null, streamFactoryFactory=null, commandListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener@29699283], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@5d32c1c7, com.mongodb.Jep395RecordCodecProvider@a6dffdb, com.mongodb.KotlinCodecProvider@40ac0a56]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[180.181.49.243:28000], srvServiceName=mongodb, mode=MULTIPLE, requiredClusterType=REPLICA_SET, requiredReplicaSetName=\'rs_gdmxnspm\', serverSelector=\'null\', clusterListeners=\'[]\', serverSelectionTimeout=\'10000 ms\', localThreshold=\'15 ms\'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener@25b4754a], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners=\'[]\', serverMonitorListeners=\'[]\'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName=\'null\', compressorList=[], uuidRepresentation=JAVA_LEGACY, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:36',
    tag: "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-180.181.49.243:28000]",
    level: 'INFO',
    type: 'org.mongodb.driver.cluster',
    message:
      "Monitor thread successfully connected to server with description ServerDescription{address=180.181.49.243:28000, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=87318574, setName='rs_gdmxnspm', canonicalAddress=dbnspdlm2mxr102.dev.mx.corp:28000, hosts=[dbnspdlm2mxr102.dev.mx.corp:28000], passives=[], arbiters=[], primary='dbnspdlm2mxr102.dev.mx.corp:28000', tagSet=TagSet{[]}, electionId=7fffffff0000000000000011, setVersion=2, topologyVersion=TopologyVersion{processId=65862abe53dde45086eaea42, counter=6}, lastWriteDate=Fri Dec 29 12:17:33 CST 2023, lastUpdateTimeNanos=1169679914448233}",
    tags: [
      "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-180.181.49.243:28000]",
      'INFO',
    ],
  },
  {
    date: '23-12-29',
    time: '12:17:36',
    tag: "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-180.181.49.243:28000]",
    level: 'INFO',
    type: 'org.mongodb.driver.cluster',
    message:
      'Adding discovered server dbnspdlm2mxr102.dev.mx.corp:28000 to client view of cluster',
    tags: [
      "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-180.181.49.243:28000]",
      'INFO',
    ],
  },
  {
    date: '23-12-29',
    time: '12:17:36',
    tag: "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-180.181.49.243:28000]",
    level: 'INFO',
    type: 'org.mongodb.driver.cluster',
    message:
      'Server 180.181.49.243:28000 is no longer a member of the replica set.  Removing from client view of cluster.',
    tags: [
      "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-180.181.49.243:28000]",
      'INFO',
    ],
  },
  {
    date: '23-12-29',
    time: '12:17:36',
    tag: "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-dbnspdlm2mxr102.dev.mx.corp:28000]",
    level: 'INFO',
    type: 'org.mongodb.driver.cluster',
    message:
      "Monitor thread successfully connected to server with description ServerDescription{address=dbnspdlm2mxr102.dev.mx.corp:28000, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=58793691, setName='rs_gdmxnspm', canonicalAddress=dbnspdlm2mxr102.dev.mx.corp:28000, hosts=[dbnspdlm2mxr102.dev.mx.corp:28000], passives=[], arbiters=[], primary='dbnspdlm2mxr102.dev.mx.corp:28000', tagSet=TagSet{[]}, electionId=7fffffff0000000000000011, setVersion=2, topologyVersion=TopologyVersion{processId=65862abe53dde45086eaea42, counter=6}, lastWriteDate=Fri Dec 29 12:17:33 CST 2023, lastUpdateTimeNanos=1169680401289648}",
    tags: [
      "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-dbnspdlm2mxr102.dev.mx.corp:28000]",
      'INFO',
    ],
  },
  {
    date: '23-12-29',
    time: '12:17:36',
    tag: "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-dbnspdlm2mxr102.dev.mx.corp:28000]",
    level: 'INFO',
    type: 'org.mongodb.driver.cluster',
    message:
      'Discovered replica set primary dbnspdlm2mxr102.dev.mx.corp:28000 with max election id 7fffffff0000000000000011 and max set version 2',
    tags: [
      "[cluster-ClusterId{value='658f0d402797757b1a45538f', description='null'}-dbnspdlm2mxr102.dev.mx.corp:28000]",
      'INFO',
    ],
  },
  {
    date: '23-12-29',
    time: '12:17:37',
    tag: '[main]',
    level: 'INFO',
    type: 'm.c.s.o.util.config.PropertiesConfig',
    message: 'Flujos cargados: {N2=Flow(idProduct=06, idSubProduct=0014)}',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:37',
    tag: '[main]',
    level: 'INFO',
    type: 'o.h.validator.internal.util.Version',
    message: 'HV000001: Hibernate Validator 8.0.1.Final',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:40',
    tag: '[main]',
    level: 'INFO',
    type: 'o.s.b.a.e.web.EndpointLinksResolver',
    message: "Exposing 2 endpoint(s) beneath base path '/actuator'",
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:40',
    tag: '[main]',
    level: 'INFO',
    type: 'o.a.coyote.http11.Http11NioProtocol',
    message: 'Starting ProtocolHandler ["http-nio-8080"]',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:40',
    tag: '[main]',
    level: 'INFO',
    type: 'o.s.b.w.e.tomcat.TomcatWebServer',
    message: "Tomcat started on port 8080 (http) with context path ''",
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:40',
    tag: '[main]',
    level: 'INFO',
    type: 'm.c.s.o.a.MxObuGblOrqAppianApplication',
    message:
      'Started MxObuGblOrqAppianApplication in 12.429 seconds (process running for 14.092)',
    tags: ['[main]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:54',
    tag: '[http-nio-8080-exec-1]',
    level: 'INFO',
    type: 'o.a.c.c.C.[Tomcat].[localhost].[/]',
    message:
      "Initializing Spring LoggableDispatcherServlet 'dispatcherRegistration'",
    tags: ['[http-nio-8080-exec-1]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:54',
    tag: '[http-nio-8080-exec-1]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: "Initializing Servlet 'dispatcherRegistration'",
    tags: ['[http-nio-8080-exec-1]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:54',
    tag: '[http-nio-8080-exec-1]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Completed initialization in 2 ms',
    tags: ['[http-nio-8080-exec-1]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:54',
    tag: '[http-nio-8080-exec-1]',
    level: 'ERROR',
    type: 'm.c.s.o.u.e.ControllerExceptionHandler',
    message:
      'Error en la ejecucion: org.springframework.web.servlet.resource.NoResourceFoundException: No static resource .',
    tags: ['[http-nio-8080-exec-1]', 'ERROR'],
  },
  {
    date: '23-12-29',
    time: '12:17:55',
    tag: '[http-nio-8080-exec-1]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /',
    tags: ['[http-nio-8080-exec-1]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:55',
    tag: '[http-nio-8080-exec-1]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: HEAD',
    tags: ['[http-nio-8080-exec-1]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:17:55',
    tag: '[http-nio-8080-exec-1]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 500',
    tags: ['[http-nio-8080-exec-1]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-2]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /swagger-ui/index.html',
    tags: ['[http-nio-8080-exec-2]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-2]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-2]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-2]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-2]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-3]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /swagger-ui/swagger-ui.css',
    tags: ['[http-nio-8080-exec-3]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-3]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-3]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-3]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-3]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-5]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /swagger-ui/index.css',
    tags: ['[http-nio-8080-exec-5]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-5]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-5]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-5]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-5]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /swagger-ui/swagger-ui-bundle.js',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /swagger-ui/swagger-ui-standalone-preset.js',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /swagger-ui/swagger-initializer.js',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /swagger-ui/favicon-32x32.png',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-9]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /v3/api-docs/swagger-config',
    tags: ['[http-nio-8080-exec-9]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-9]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-9]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:53',
    tag: '[http-nio-8080-exec-9]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-9]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:56',
    tag: '[http-nio-8080-exec-4]',
    level: 'INFO',
    type: 'o.s.api.AbstractOpenApiResource',
    message: 'Init duration for springdoc-openapi is: 2266 ms',
    tags: ['[http-nio-8080-exec-4]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:56',
    tag: '[http-nio-8080-exec-4]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /v3/api-docs',
    tags: ['[http-nio-8080-exec-4]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:56',
    tag: '[http-nio-8080-exec-4]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: GET',
    tags: ['[http-nio-8080-exec-4]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:23:56',
    tag: '[http-nio-8080-exec-4]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-4]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:26',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.appian.service.AppianService',
    message:
      'Producto: N2, Paso: PREEXISTENCE, Folio: 9e58a9b0-5cde-4752-a413-7d7efa00a8f3',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:26',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>REQUEST APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:26',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{"idCanal":"3","numeroFolio":"9e58a9b0-5cde-4752-a413-7d7efa00a8f3","idAccionFk":"181","nombreCaso":"N2","idEstadoFk":"181","idTipoCasoFk":"221","idPasoFk":"202","datos":{"geolocalizacion":{"latitud":"19.423734","longitud":"-98.932162","sessionId":"ceaf4567-c0b4-432a-85b3-0ad06ab7ff53","terminosCondiciones":true,"avisoPrivacidad":true,"ciudadLocalizacion":"CHIMALHUACAN","estadoLocalizacion":"ESTADO DE MEXICO","direccionCliente":"10.2.2.2"},"preexistencia":{"nombre":"ISAIAS","apellidoP":"ACERA","apellidoM":"CAMPANA","genero":"M","fechaNacimiento":"1971-08-23","cardIdentificationCode":"123456788","curp":"AECI710823HDFCMS00","paisNacimiento":"052","estadoCivil":"Single"}}}',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:26',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------REQUEST APPIAN------------------------------',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{\\"data\\":{\\"startDate_dt\\":null,\\"executionTime\\":null,\\"endDate_dt\\":\\"2023-12-29T18:28:27.512Z\\",\\"status\\":\\"success\\",\\"parameters\\":{\\"folio\\":\\"9e58a9b0-5cde-4752-a413-7d7efa00a8f3\\",\\"idAplicacion\\":1,\\"idCanal\\":1,\\"idProducto\\":1,\\"idSubproducto\\":1,\\"clientId\\":1,\\"clientSecret\\":1,\\"consecutivo\\":1,\\"idAccion\\":1,\\"idTipoCaso\\":1,\\"fechaPeticion\\":\\"2023-12-29T18:28:27.512Z\\",\\"pantallaSiguiente\\":\\"colectivos_01\\",\\"idEstadoSiguiente\\":\\"181\\",\\"descEstadoSiguiente\\":\\"Solicitando N2\\",\\"idPasoSiguientes\\":\\"204\\",\\"descPasoSiguiente\\":\\"colectivos_01\\",\\"respuesta\\":{\\"caso\\":\\"400\\",\\"datos\\":[{\\"OD23statusCode\\":408,\\"descripcion\\":\\"Failed to connect to https://api18.dev.mx.corp/santander-mexico/intranet-dev/customer-precedents-inquiry-oa2p/v1/salesAndServices/customerManagement/customerPrecedents/customerPrecedentsInq/negativeFiles/persons/names/ISAIAS/ACERA/birthDays/1971-08-23\\",\\"statusCode\\":400}]}}},\\"notifications\\":[{\\"code\\":\\"EXC.200\\",\\"level\\":\\"Ok\\",\\"message\\":\\"Operacion exitosa\\",\\"timestamp\\":\\"2023-12-29T12:28:51:079Z\\",\\"moreInfo\\":\\"\\"}]}',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /api/v1/obu/case/N2/preexistence/casemanagement',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: POST',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-7]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-7]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.appian.service.AppianService',
    message:
      'Producto: N2, Paso: COLLECTIVE, Folio: 9e58a9b0-5cde-4752-a413-7d7efa00a8f3',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>REQUEST APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{"idCanal":"3","numeroFolio":"9e58a9b0-5cde-4752-a413-7d7efa00a8f3","idAccionFk":"181","idTipoCasoFk":"221","screenId":"colectivos_01","stepId":"204","stateId":"181","datos":{"universidades":{"intentoUni":0,"openMarket":true}}}',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:51',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------REQUEST APPIAN------------------------------',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{\\"data\\":{\\"startDate_dt\\":null,\\"executionTime\\":null,\\"endDate_dt\\":\\"2023-12-29T18:28:52.969Z\\",\\"status\\":\\"success\\",\\"parameters\\":{\\"folio\\":\\"9e58a9b0-5cde-4752-a413-7d7efa00a8f3\\",\\"idAplicacion\\":1,\\"idCanal\\":1,\\"idProducto\\":1,\\"idSubproducto\\":1,\\"clientId\\":1,\\"clientSecret\\":1,\\"consecutivo\\":1,\\"idAccion\\":1,\\"idTipoCaso\\":1,\\"fechaPeticion\\":\\"2023-12-29T18:28:52.969Z\\",\\"pantallaSiguiente\\":\\"colectivos_01\\",\\"idEstadoSiguiente\\":\\"181\\",\\"descEstadoSiguiente\\":\\"Solicitando N2\\",\\"idPasoSiguientes\\":\\"207\\",\\"descPasoSiguiente\\":\\"datos_contacto_04\\",\\"respuesta\\":{\\"caso\\":\\"CM200\\",\\"datos\\":[{\\"edoEvaluacion\\":\\"Continua\\",\\"descripcion\\":\\"OK\\",\\"statusCode\\":200}]}}},\\"notifications\\":[{\\"code\\":\\"EXC.200\\",\\"level\\":\\"Ok\\",\\"message\\":\\"Operacion exitosa\\",\\"timestamp\\":\\"2023-12-29T12:28:53:472Z\\",\\"moreInfo\\":\\"\\"}]}',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /api/v1/obu/case/N2/collective/casemanagement',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: POST',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:28:53',
    tag: '[http-nio-8080-exec-6]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-6]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:45:44',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.appian.service.AppianService',
    message:
      'Producto: N2, Paso: PREEXISTENCE, Folio: 70abaf06-f233-4ede-b371-426c52fbece1',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:45:44',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>REQUEST APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:45:44',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{"idCanal":"3","numeroFolio":"70abaf06-f233-4ede-b371-426c52fbece1","idAccionFk":"181","nombreCaso":"N2","idEstadoFk":"181","idTipoCasoFk":"221","idPasoFk":"202","datos":{"geolocalizacion":{"latitud":"19.423734","longitud":"-98.932162","sessionId":"ceaf4567-c0b4-432a-85b3-0ad06ab7ff53","terminosCondiciones":true,"avisoPrivacidad":true,"ciudadLocalizacion":"CHIMALHUACAN","estadoLocalizacion":"ESTADO DE MEXICO","direccionCliente":"10.2.2.2"},"preexistencia":{"nombre":"ISAIAS","apellidoP":"ACERA","apellidoM":"CAMPANA","genero":"M","fechaNacimiento":"1971-08-23","cardIdentificationCode":"123456788","curp":"AECI710823HDFCMS00","paisNacimiento":"052","estadoCivil":"Single"}}}',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:45:44',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------REQUEST APPIAN------------------------------',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{\\"data\\":{\\"startDate_dt\\":null,\\"executionTime\\":null,\\"endDate_dt\\":\\"2023-12-29T18:45:44.697Z\\",\\"status\\":\\"success\\",\\"parameters\\":{\\"folio\\":\\"70abaf06-f233-4ede-b371-426c52fbece1\\",\\"idAplicacion\\":1,\\"idCanal\\":1,\\"idProducto\\":1,\\"idSubproducto\\":1,\\"clientId\\":1,\\"clientSecret\\":1,\\"consecutivo\\":1,\\"idAccion\\":1,\\"idTipoCaso\\":1,\\"fechaPeticion\\":\\"2023-12-29T18:45:44.697Z\\",\\"pantallaSiguiente\\":\\"colectivos_01\\",\\"idEstadoSiguiente\\":\\"181\\",\\"descEstadoSiguiente\\":\\"Solicitando N2\\",\\"idPasoSiguientes\\":\\"204\\",\\"descPasoSiguiente\\":\\"colectivos_01\\",\\"respuesta\\":{\\"caso\\":\\"400\\",\\"datos\\":[{\\"OD23statusCode\\":408,\\"descripcion\\":\\"Failed to connect to https://api18.dev.mx.corp/santander-mexico/intranet-dev/customer-precedents-inquiry-oa2p/v1/salesAndServices/customerManagement/customerPrecedents/customerPrecedentsInq/negativeFiles/persons/names/ISAIAS/ACERA/birthDays/1971-08-23\\",\\"statusCode\\":400}]}}},\\"notifications\\":[{\\"code\\":\\"EXC.200\\",\\"level\\":\\"Ok\\",\\"message\\":\\"Operacion exitosa\\",\\"timestamp\\":\\"2023-12-29T12:46:08:205Z\\",\\"moreInfo\\":\\"\\"}]}',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /api/v1/obu/case/N2/preexistence/casemanagement',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: POST',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-8]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-8]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.appian.service.AppianService',
    message:
      'Producto: N2, Paso: COLLECTIVE, Folio: 70abaf06-f233-4ede-b371-426c52fbece1',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>REQUEST APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{"idCanal":"3","numeroFolio":"70abaf06-f233-4ede-b371-426c52fbece1","idAccionFk":"181","idTipoCasoFk":"221","screenId":"colectivos_01","stepId":"204","stateId":"181","datos":{"universidades":{"intentoUni":0,"openMarket":true}}}',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:08',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------REQUEST APPIAN------------------------------',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:10',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:10',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '{\\"data\\":{\\"startDate_dt\\":null,\\"executionTime\\":null,\\"endDate_dt\\":\\"2023-12-29T18:46:10.108Z\\",\\"status\\":\\"success\\",\\"parameters\\":{\\"folio\\":\\"70abaf06-f233-4ede-b371-426c52fbece1\\",\\"idAplicacion\\":1,\\"idCanal\\":1,\\"idProducto\\":1,\\"idSubproducto\\":1,\\"clientId\\":1,\\"clientSecret\\":1,\\"consecutivo\\":1,\\"idAccion\\":1,\\"idTipoCaso\\":1,\\"fechaPeticion\\":\\"2023-12-29T18:46:10.108Z\\",\\"pantallaSiguiente\\":\\"colectivos_01\\",\\"idEstadoSiguiente\\":\\"181\\",\\"descEstadoSiguiente\\":\\"Solicitando N2\\",\\"idPasoSiguientes\\":\\"207\\",\\"descPasoSiguiente\\":\\"datos_contacto_04\\",\\"respuesta\\":{\\"caso\\":\\"CM200\\",\\"datos\\":[{\\"edoEvaluacion\\":\\"Continua\\",\\"descripcion\\":\\"OK\\",\\"statusCode\\":200}]}}},\\"notifications\\":[{\\"code\\":\\"EXC.200\\",\\"level\\":\\"Ok\\",\\"message\\":\\"Operacion exitosa\\",\\"timestamp\\":\\"2023-12-29T12:46:10:675Z\\",\\"moreInfo\\":\\"\\"}]}',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:10',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.a.r.AppianRepository',
    message:
      '------------------------------>RESPONSE APPIAN<------------------------------',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:10',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'Path:       /api/v1/obu/case/N2/collective/casemanagement',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:10',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpMethod: POST',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
  {
    date: '23-12-29',
    time: '12:46:10',
    tag: '[http-nio-8080-exec-10]',
    level: 'INFO',
    type: 'm.c.s.o.u.c.LoggableDispatcherServlet',
    message: 'HttpStatus: 200',
    tags: ['[http-nio-8080-exec-10]', 'INFO'],
  },
];
